# Generated by Django 2.1 on 2020-02-18 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200218_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.Comment'),
            preserve_default=False,
        ),
    ]
