# Generated by Django 2.1 on 2020-02-22 18:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0022_comment_date_commented'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_reaction',
            field=models.ManyToManyField(related_name='react', to=settings.AUTH_USER_MODEL),
        ),
    ]
