# Generated by Django 3.0.4 on 2020-03-19 07:43

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20200318_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
