# Generated by Django 3.0.4 on 2020-03-31 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='institution',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
