# Generated by Django 3.0.4 on 2020-03-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200331_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='re_solution',
            field=models.IntegerField(default=0),
        ),
    ]
