# Generated by Django 3.0.4 on 2020-03-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_re_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='...'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='institution',
            field=models.CharField(default='IIITS', max_length=100),
        ),
    ]
