# Generated by Django 3.0.4 on 2020-03-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='input_file',
            field=models.FileField(default=0, upload_to='inputs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='output_file',
            field=models.FileField(default=0, upload_to='outputs/'),
            preserve_default=False,
        ),
    ]
