# Generated by Django 3.0.4 on 2020-03-15 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0004_auto_20200314_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem_Feature',
            fields=[
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='judge.Problem')),
                ('accuracy', models.FloatField(default=0)),
                ('total_submission', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Problem_Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=20)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Problem')),
            ],
        ),
    ]
