# Generated by Django 3.0.4 on 2020-03-16 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0005_auto_20200315_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='problem',
            name='sample_input',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='sample_output',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
