# Generated by Django 3.0.4 on 2020-03-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0006_auto_20200316_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='explaination',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
