# Generated by Django 3.0.4 on 2020-03-18 10:45

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0007_problem_explaination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', froala_editor.fields.FroalaField()),
            ],
        ),
    ]
