# Generated by Django 3.0.4 on 2020-03-18 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0008_editor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Editor',
            new_name='Page',
        ),
    ]
