# Generated by Django 3.0.4 on 2020-03-18 16:57

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0009_auto_20200318_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='statement',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
