# Generated by Django 3.0.4 on 2020-03-19 04:54

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0010_auto_20200318_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='constraint',
            field=froala_editor.fields.FroalaField(blank='true'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='statement',
            field=froala_editor.fields.FroalaField(blank='true'),
        ),
    ]
