# Generated by Django 3.0.4 on 2020-03-19 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0011_auto_20200319_1024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
