# Generated by Django 3.0.4 on 2020-03-31 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('judge', '0012_delete_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('hrating', models.IntegerField(default=0)),
                ('star', models.IntegerField(default=1)),
                ('rank', models.IntegerField(blank='true')),
                ('ac_solution', models.IntegerField(default=0)),
                ('wa_solution', models.IntegerField(default=0)),
                ('tle_solution', models.IntegerField(default=0)),
                ('ce_solution', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
