# Generated by Django 3.0.4 on 2020-03-31 05:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('judge', '0013_user_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_info',
            new_name='Info',
        ),
    ]
