# Generated by Django 3.0.4 on 2020-03-31 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0014_auto_20200331_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='rank',
        ),
    ]
