# Generated by Django 3.0.4 on 2020-03-31 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0015_remove_info_rank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
    ]
