# Generated by Django 3.0.4 on 2020-04-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0017_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='absolute',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
