# Generated by Django 3.0.4 on 2020-04-01 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('judge', '0018_graph_absolute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='profile',
        ),
        migrations.AddField(
            model_name='graph',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
