# Generated by Django 3.0.4 on 2020-04-01 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0019_auto_20200401_1549'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Graph',
        ),
    ]
