# Generated by Django 3.0.4 on 2020-04-01 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0023_rtgraph'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RGraph',
        ),
    ]
