# Generated by Django 3.0.4 on 2020-04-01 10:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('judge', '0024_delete_rgraph'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RtGraph',
            new_name='Graph',
        ),
    ]
