# Generated by Django 3.0.3 on 2020-03-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='language',
            field=models.CharField(max_length=100),
        ),
    ]
