# Generated by Django 3.0.3 on 2020-03-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0003_program_sol_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sol_id', models.TextField()),
                ('sol_in', models.FileField(upload_to='./media/input')),
                ('sol_out', models.FileField(upload_to='./media/output')),
                ('sol_time', models.IntegerField(default=True)),
            ],
        ),
    ]
