# Generated by Django 3.0.3 on 2020-03-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0004_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='q_id',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
