# Generated by Django 3.0.3 on 2020-03-15 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0005_program_q_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='q_id',
            new_name='sol_id',
        ),
    ]
